name = "avatar-remix-bot"
main = "src/index.ts"
compatibility_date = "2023-01-24"

[[queues.producers]]
queue = "avatar-remix-jobs"
binding = "AVATAR_REMIX_JOBS"

[[queues.consumers]]
queue = "avatar-remix-jobs"
max_batch_size = 6    # optional: defaults to 10
max_batch_timeout = 1 # optional: defaults to 5 seconds

[vars]
DISCORD_PUBLIC_KEY = '6ebc1a23ce676ede92f44f0bf943af50b87a75a693cbe3c1d2ccbf353eaa220c'
DISCORD_APPLICATION_ID = '1234567890123456789'

WORKER_BASE_URL = 'https://avatar-remix-bot.<yourname>.workers.dev'

REPLICATE_INSTRUCT_PIX2PIX_MODEL_VERSION = '30c1d0b916a6f8efce20493f5d61ee27491ab2a60437c13c588468b9810ec23f'
REPLICATE_ESRGAN_MODEL_VERSION = '42fed1c4974146d4d2414e2be2c5277c7fcf05fcc3a73abf41610695738c1d7b'

[env.production]
kv_namespaces = [
  { binding = "AVATAR_REMIX_FOLLOWUPS", id = "abc123" }
]
